### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by tamalsaha** [crazy-max/ghaction-docker-buildx#11]
Hi,
I just wanted to say thank you for this project. We started using GitHub actions recently and needed a way to use docker buildx. You project has made it very easy for us to use docker buildx in GitHub actions. It is working great!

-Tamal

**Comment by crazy-max** [comment]
@tamalsaha And thanks for your feedback! :heart: Glad you enjoy it :rocket:

**Comment by tamalsaha** [comment]
Will sure do. We also use Hugo :)

**Comment by crazy-max** [comment]
@tamalsaha Also keep in mind you should use `v1` tag rather than `master` for this action as [specified by GitHub](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md) to avoid any regressions.
