### ISSUE TITLE
Previous failed "docker buildx build" job on the same runner fails next run

### ISSUE THREAD

**Issue by rbellamy** [crazy-max/ghaction-docker-buildx#112]
I'm running buildx on a self-hosted runner, which means that two jobs in the same workflow will run on the same host. If a previous job that uses this action fails for whatever reason (not necessarily a failure in this action), this action fails to finish in all subsequent jobs with the error below:

```shell script
🔨 Creating a new builder instance...
/usr/bin/docker buildx create --name builder --driver docker-container --use
existing instance for builder but no append mode, specify --node to make changes for existing instances
##[error]The process '/usr/bin/docker' failed with exit code 1
```

My current workaround is to `docker buildx rm builder`

**Comment by crazy-max** [comment]
Hi @rbellamy, I just saw the connection with your PR #114. Indeed if your runners are not ephemeral it may be a problem.

**Comment by crazy-max** [comment]
I think that the best way is to remove the builder in your workflow with something like this:

```
steps:
  ...
  - name: Remove builder
    if: always()
    run: docker buildx rm builder || true
```

**Comment by rbellamy** [comment]
That's certainly an option, and now that you mention it, I'm on the fence about my opinion.

On the one hand, I think this action should work as-is, addressing as many edge conditions for setup as possible. It should manage the fact that a later action can leave the environment in an state that this action can't address bothers me. It should address this either through the use of something like I did here or via a post-action cleanup process (taken from `@actions/checkout`):

```js
// Main
if (!stateHelper.IsPost) {
  run()
}
// Post
else {
  cleanup()
}
```

On the other hand, I recognize that you can't predict what someone is going to do with the buildx environment you are trying to setup, and you can't be responsible for "all the things." For instance, if we follow my logic above, I could see someone asking you to make sure Docker is installed too - which to me is patently outside the scope of this action.

**Comment by crazy-max** [comment]
@rbellamy Hum I didn't know about this post state. I think we could go with that on your PR.

**Comment by rbellamy** [comment]
Okay, we now have a "Post set up" process that removes the builder after the job completes.
