### ISSUE TITLE
Unable to push tagged image to registry

### ISSUE THREAD

**Issue by rgov** [crazy-max/ghaction-docker-buildx#134]
Thanks for this useful Action.

I'm trying to build my image and push it to the registry in separate steps. I try to tag the built container image as `$IMAGE_NAME` and then refer to the image by that tag when pushing.

However, I get told that `$IMAGE_NAME:latest` is unknown to Docker during the push step.

I saw in one of your examples you basically duplicate the whole `docker Buildx build` command, but shouldn't it be possible to refer to it by tag?

```yaml
 - name: Build
        run: |
          docker buildx build \
            --platform ${{ matrix.arch }} \
            --output type=image,name=$IMAGE_NAME,push=false \
            .
      - name: Log into registry
        ...

      - name: Push image
        run: |
          # re-tag the image and push
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
```

**Comment by crazy-max** [comment]
Hi @rgov,

You cannot currently retag a manifest list if you use an `image` output type. (see the official [README of buildx](https://github.com/docker/buildx/blob/master/README.md). But you can use [variable substitution like I've done on this project](https://github.com/crazy-max/diun/blob/4a696099c7e94e90092420479e7beb640edc9d8c/.github/workflows/build.yml#L93-L156).

For more info and support on buildx, go to https://github.com/docker/buildx

**Comment by rgov** [comment]
Thanks. Since you are knowledgeable about Buildx, could you please highlight for me in the README where it describes this restriction? I see several ways to tag an image, and export an image, but I don't understand the limitation against retagging.

**Comment by crazy-max** [comment]
@rgov 

`docker tag` only handles single manifest and unfortunately there is no `docker buildx tag` command at this time, that's it. You can only handle tags through `docker buildx build` command. You can do something [like this](https://github.com/crazy-max/diun/blob/4a696099c7e94e90092420479e7beb640edc9d8c/.github/workflows/build.yml#L108-L111) as a workaround.

And you cannot use `docker push` too. Everything must be handled through `docker buildx`. But again you can use a workaround to [build](https://github.com/crazy-max/diun/blob/4a696099c7e94e90092420479e7beb640edc9d8c/.github/workflows/build.yml#L132-L134) then [push](https://github.com/crazy-max/diun/blob/4a696099c7e94e90092420479e7beb640edc9d8c/.github/workflows/build.yml#L143-L146).

**Comment by rgov** [comment]
Ok, thanks! I followed your advice. However, when it pushes, I get:

```
failed to solve: rpc error: code = Unknown desc = failed commit on ref "layer-sha256:2384fa44dfc2b02fa7255bb4791a8972fbd04cea4e56683f3d955180e25afc0c": invalid content digest in response: invalid checksum digest format
```

Have you seen something like that before?

**Comment by crazy-max** [comment]
Do you have link to your repo/workflow?

**Comment by rgov** [comment]
Yes, here is the workflow: https://github.com/rgov/shairport-sync/blob/master/.github/workflows/docker.yml Thanks for taking a look.

**Comment by crazy-max** [comment]
@rgov Looking at your [login step](https://github.com/rgov/shairport-sync/blob/8f8976563283bf0e598b5d8f589fde4ce0c870e8/.github/workflows/docker.yml#L61), you try to push to the GitHub Package Registry but multi-platform Docker image are [not currently supported on it](https://github.community/t5/GitHub-API-Development-and/Handle-multi-arch-Docker-images-on-GitHub-Package-Registry/m-p/31650#M2981). See also #63.

**Comment by rgov** [comment]
I see, thanks for explaining. It would be nice to include this information in the documentation of the action.

If I define multiple images in my docker-compose.yml file, does Buildx automatically build each of them for the platforms I specify, and push them all?

**Comment by crazy-max** [comment]
@rgov 

> I see, thanks for explaining. It would be nice to include this information in the documentation of the action.

This action is not platform specific. Hope you understand I cannot cover/list all registries out there :)

> If I define multiple images in my docker-compose.yml file, does Buildx automatically build each of them for the platforms I specify, and push them all?

I don't think this is feasible through compose but maybe [`bake`](https://github.com/docker/buildx#buildx-bake-options-target) could fit your needs. Anyway, you should ask this on [docker/buildx](https://github.com/docker/buildx) directly.
