### ISSUE TITLE
Latest commit breaks the action

### ISSUE THREAD

**Issue by HenryQW** [crazy-max/ghaction-docker-buildx#150]
Hi Max,

I've been using `crazy-max/ghaction-docker-buildx@master` for a while now (I probably shouldn't do that), the latest commit seems to break it.

##[error]Could not find file '/home/runner/work/_actions/_temp_284a9c8c-aac8-4c95-8bb4-8306bdefd34f/_staging/crazy-max-ghaction-docker-buildx-4464eda/node_modules/.bin/seek-bunzip'.

I've switched to `crazy-max/ghaction-docker-buildx@v1` and the problem is gone.

**Comment by crazy-max** [comment]
Hi @HenryQW,

Will fix that asap, thanks for your input.

**Comment by crazy-max** [comment]
Should be fixed now.
