### ISSUE TITLE
Getting 403 response from GitHub

### ISSUE THREAD

**Issue by cglewis** [crazy-max/ghaction-docker-buildx#183]
I'm using this on several projects and they all started doing this just today:
```
Run crazy-max/ghaction-docker-buildx@v1.6.0
✅ Buildx version found: v0.4.1
⬇️ Downloading https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64...
##[error]Unexpected HTTP response: 403
```

The yaml for that step is pretty vanilla:
```
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1.6.0
      with:
        buildx-version: latest
        qemu-version: latest
```

I just updated to 1.6.0 today, it's also broken on 1.4.0 which is what I was using before.

**Comment by crazy-max** [comment]
Hi @cglewis, do you have a line to your repo pls?

**Comment by crazy-max** [comment]
@cglewis Ok just found it's https://github.com/CyberReboot/poseidon. I will try to reproduce with your workflow. Keep you in touch.

**Comment by crazy-max** [comment]
@cglewis Cannot reproduce with [this workflow](https://github.com/crazy-max/docker-7zip/runs/654707149?check_suite_focus=true#step:3:6). There is maybe a limitation if your org triggers to much calls to the download release endpoint.

**Comment by cglewis** [comment]
Huh. I've never run into limits before. Interesting. I'll try it out later and see if resolves itself. Thanks for looking into it!

**Comment by crazy-max** [comment]
@cglewis

> Huh. I've never run into limits before

Me neither and I download assets through many other actions I made so I'm pretty worried about it :sweat_smile:

> Thanks for looking into it!

Sure you're welcome

**Comment by cglewis** [comment]
@crazy-max I just retriggered the workflow, to see if it worked, and seems happy again. Could have been a GitHub/S3 issue. I'm going to close this for now, but will reopen if I run into the issue again. Thanks again for an awesome project and the quick response!

**Comment by crazy-max** [comment]
@cglewis

> I just retriggered the workflow, to see if it worked, and seems happy again. Could have been a GitHub/S3 issue. I'm going to close this for now, but will reopen if I run into the issue again. 

I was going to say the same thing to you, it seems to happen with the HEAD response returning a 403 from S3 indeed. Let's keep an eye on it. I'll do some more research of my own.

> Thanks again for an awesome project and the quick response!

:handshake:

**Comment by crazy-max** [comment]
@cglewis Next time you've got this issue, please add the secret [`ACTIONS_STEP_DEBUG`](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#how-to-access-step-debug-logs) to `true` on your repo.

**Comment by crazy-max** [comment]
@cglewis Ok this is an [incident with GitHub](https://www.githubstatus.com/incidents/1p369ttzrnqy).

![image](https://user-images.githubusercontent.com/1951866/81353698-0d59bd80-90ca-11ea-82ba-c1cd34024863.png)

**Comment by cglewis** [comment]
Ahh! Nice find!

**Comment by crazy-max** [comment]
To avoid this problem in the future, I will use the runner cache system to avoid re-downloading buildx at each build if the version did not changed.

**Comment by crazy-max** [comment]
@cglewis Cache of Buildx binary is now implemented.
