### ISSUE TITLE
`authorization failed` trying to --push to dockerhub

### ISSUE THREAD

**Issue by iav** [crazy-max/ghaction-docker-buildx#199]
Got `authorization failed` trying to do `docker build buildx --push` to dockerhub.

no error:
```
 echo -e "from alpine\n  run echo hello! \n \n" | tee dtest
 docker buildx build -f dtest -t dtest -t shtripok/rust-musl-builder:dtest-load --load .
docker push shtripok/rust-musl-builder:dtest-load
```
and immediately after, in same script:
`docker buildx build -f dtest -t dtest -t shtripok/rust-musl-builder:dtest-push --push .`
error.

Line in action script https://github.com/iav/rust-musl-builder/blob/arm/.github/workflows/dh-build.yml#L106
related log line: https://github.com/iav/rust-musl-builder/runs/729084875#step:9:464

**Comment by crazy-max** [comment]
@iav See #97

**Comment by dennybaa** [comment]
Hey @crazy-max . Could please you give a clue. This is odd, people keep getting this... I must be missing something.

```
#21 ERROR: server message: insufficient_scope: authorization failed
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed
```

Prior to push which fails with the above error, login to docker hub has succeed 100%.

```
echo "***" | docker login -u "${DOCKER_USERNAME}" --password-stdin

WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

btw when I use buildx locally push works, so i'm kinda lost.

thank you, great stuff :bow:
