### ISSUE TITLE
auto-push is currently not implemented for docker driver

### ISSUE THREAD

**Issue by segator** [crazy-max/ghaction-docker-buildx#222]
trying to build for linux amd64 arm64 and arm/v7 
then 
```
auto-push is currently not implemented for docker driver
```

**Comment by crazy-max** [comment]
Please create a proper [bug report](https://github.com/crazy-max/ghaction-docker-buildx/issues/new?template=bug_report.md).

**Comment by segator** [comment]
I fixed it :) in case other people have this issue, is fixed as soon you execute something like this,
could you update the readme to add this? or even better if this can be automatically executed in the action.
```
docker buildx create --name mybuilder
docker buildx use mybuilder
docker buildx inspect --bootstrap
```

**Comment by crazy-max** [comment]
@segator,

> or even better if this can be automatically executed in the action.

 It's basically what this action do.
