### ISSUE TITLE
Move to Docker organization

### ISSUE THREAD

**Issue by crazy-max** [crazy-max/ghaction-docker-buildx#234]
I plan to archive this repository following the work I did with the Docker team on an action that will be formalized in their organization: https://github.com/docker/setup-buildx-action

There will be a total of 4 actions:

* [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action)
* [docker/setup-qemu-action](https://github.com/docker/setup-qemu-action)
* [docker/login-action](https://github.com/docker/login-action)
* [docker/build-push-action](https://github.com/docker/build-push-action)

I have also created [another repo](https://github.com/crazy-max/test-docker-action) to check the behavior of these actions: [ci.yml](https://github.com/crazy-max/test-docker-action/blob/master/.github/workflows/ci.yml) / [full.yml](https://github.com/crazy-max/test-docker-action/blob/master/.github/workflows/full.yml).

A [real example](https://github.com/crazy-max/diun/blob/e9c047f4aabbf58f0e44372c500fd8d6b5b47998/.github/workflows/build.yml#L84-L143) is available on [this repo](https://github.com/crazy-max/diun).

You can already try them out and report any issues you may encounter.

**Comment by ttshivers** [comment]
In your examples, I notice you don't use any caching actions for the docker builds.

**Comment by crazy-max** [comment]
@ttshivers See https://github.com/docker/build-push-action/tree/v2#leverage-github-cache as an example

**Comment by scyto** [comment]
lol, just setup this version, does the official version  have all the same features and syntax?

**Comment by scyto** [comment]
I only just found this solution, been looking for something like this for 2+ years. It's awesome.  I implemented crazy-max's native solution first. Then found this bug so rebuilt in new docker owned variant.  Their documentation is more confusing; but got it all sorted. 

If anyone is interested this is what a complete non-programmer, who had never seen this before, managed in ~6 hours - most of that was troubleshooting the weird rpc bug on push (tl;dr its random and i can't, as you all know!)

https://github.com/scyto/infinitude 

@crazy-max sent you a thanks.
Alex

**Comment by scyto** [comment]
> In your examples, I notice you don't use any caching actions for the docker builds.

I just implemented the cache, not sure what it really buys me as even with zero dockerfile changes it rebuilds all architecture tags from the ground up?  It didn't reduce the time when the cache was used....

**Comment by crazy-max** [comment]
v1.0.0 of [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action) is [now available](https://github.com/docker/setup-buildx-action/releases/tag/v1.0.0) and [published to the marketplace](https://github.com/marketplace/actions/docker-setup-buildx). This action will be archived and user prompted to use the official Docker action.
