### ISSUE TITLE
How to login to github registry

### ISSUE THREAD

**Issue by ViceIce** [crazy-max/ghaction-docker-buildx#63]
I would like to use the github packages registry for caching. How to i correctly login?

**Comment by crazy-max** [comment]
@ViceIce Fyi, [multi-arch Docker image are not currently handled on GitHub Package Registry](https://github.community/t5/GitHub-API-Development-and/Handle-multi-arch-Docker-images-on-GitHub-Package-Registry/m-p/31650#M2981).

**Comment by ViceIce** [comment]
Thanks, i found it too. Very anoying. Thanks for your help.
