### ISSUE TITLE
Question: Cache

### ISSUE THREAD

**Issue by jjangga0214** [crazy-max/ghaction-docker-buildx#79]
I saw your comment [here](https://github.community/t5/GitHub-Actions/Cache-a-Docker-image-built-in-workflow/m-p/32468/highlight/true#M1143)

![Screenshot from 2020-01-19 15-12-27](https://user-images.githubusercontent.com/28584151/72675962-2dd81a80-3acf-11ea-8c1a-c75358494d6f.png)

I'm curious about this. How would it be possible? Cache generated while building docker images should not be necessarily persisted in the same physical machine? (Maybe that's because I don't know buildkit or buildx well)

And what do you mean by `does not require to push to registry`, more concretely?

Regardless of the answer, thank you for making this action!

**Comment by crazy-max** [comment]
@jjangga0214 

> Cache generated while building docker images should not be necessarily persisted in the same physical machine?

Indeed, with buildx, cache can be imported from registry as stipulated in [this section](https://github.com/docker/buildx#--cache-fromnametypetypekeyvalue).

> And what do you mean by `does not require to push to registry`, more concretely?

What I forgot to say here is about the [`--output` flag](https://github.com/docker/buildx#-o---outputpath-typetypekeyvalue). `"type=image,push=false"` value for it allow to write the build result as  a manifest list in my case and can be used later to push to registry in the same job. Take a look at [this workflow](https://github.com/crazy-max/docker-fail2ban/blob/master/.github/workflows/build.yml#L41-L70) for example.

But I think you want to know more about caching across builds/jobs. In that case you can use [`--cache-to` flag](https://github.com/docker/buildx#--cache-tonametypetypekeyvalue) to do that with something like:

`docker buildx build --cache-to=type=local,dest=path/to/cache .`

Not tested but in your workflow you can then use the official cache action like this:

```
- uses: actions/cache@v1
  with:
    path: path/to/cache
    key: ${{ runner.os }}-docker-buildx-${{ hashFiles('**/Dockerfile') }}
    restore-keys: |
      ${{ runner.os }}-docker-buildx-
```
