### ISSUE TITLE
How to push to DockerHub

### ISSUE THREAD

**Issue by Yooooomi** [crazy-max/ghaction-docker-buildx#97]
Hello, I'm using your action to build my image to several architecure. I would like to know how can I then push the built image to dockerhub ?

Thank you

**Comment by crazy-max** [comment]
Hi @Yooooomi,

It depends on which flags you use when you build the image with buildx. You can control whether or not the image will be pushed into a registry with the [`--output` flag](https://github.com/docker/buildx#-o---outputpath-typetypekeyvalue).

A concrete example can be found on the repository [crazy-max/diun](https://github.com/crazy-max/diun). And to be more specific, it's about [this job](https://github.com/crazy-max/diun/blob/06d8974fe6b32204cf4099a6fcf10aee75e2adf5/.github/workflows/build.yml#L76-L144).

**Comment by Yooooomi** [comment]
Yeah I managed to resolve it by `docker login`'ing just after the buildx setup using the secrets of my repo as docker credentials
